### ISSUE TITLE
add nvidia

### ISSUE THREAD

**Issue by charagarlnad** [dm4uz3/xorg-fix-your-shit#1]
add nvidia
this was gonna be a shitpost but i found the xorg conf to fix nvidia tearing so it isnt now
https://wiki.archlinux.org/index.php/NVIDIA/Troubleshooting#Avoid_screen_tearing

**Comment by dm4uz3** [comment]
pull request it in lazy ass

**Comment by charagarlnad** [comment]
hello yes #2 exists now closing

**Comment by dm4uz3** [comment]
took you a while
